name: Build .NET Core API

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '3.0.x'
      - name: Restore dependencies
        run: dotnet restore ApiTutorial.sln
      - name: Build
        run: dotnet build ApiTutorial.sln --configuration Release --no-restore
      - name: Test (if exists)
        run: |
          if [ -f "ApiTutorial.Tests.csproj" ]; then
            dotnet test ApiTutorial.Tests.csproj --no-build --verbosity normal
          else
            echo "No test project found."
          fi
